cat <<'EOF' > kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: wp-prod
resources:
  - namespace.yaml
  - mariadb-secret.yaml
  - mariadb-statefulset.yaml
  - mariadb-service.yaml
  - wordpress-secret.yaml
  - wordpress-deployment.yaml
  - wordpress-service.yaml
EOF
