apiVersion: v1
kind: Secret
metadata:
  name: mariadb-secret
  namespace: wp-prod
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: riam
  MYSQL_USER: wordpress
  MYSQL_PASSWORD: riam
  MYSQL_DATABASE: wordpress

