apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  namespace: wp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress:6.4
        env:
        - name: WORDPRESS_DB_HOST
          value: mariadb.wp-prod.svc.cluster.local:3306
        - name: WORDPRESS_DB_NAME
          value: wordpress         # Base correcte
        - name: WORDPRESS_DB_USER
          value: wordpress         # Utilisateur correct
        - name: WORDPRESS_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: wordpress-secret
              key: wordpress-db-password
        ports:
        - containerPort: 80

