apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: wp-prod
spec:
  type: NodePort
  selector:
    app: wordpress
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30081  # différent de 30080 pour éviter conflit

